name: string_unescape
description: Handy utility to unescape string representation (unicode, newline, tab, etc).
version: 1.5.1
# homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
